var langs = {
    accessSetting: { pr: "جزئیات دسترسی", en: "Access Setting", fr: "accéder au réglage" },
    accountDescription: { pr: "شرح", en: "Account Description", fr: "description du compte" },
    accounting: { pr: "حسابداری", en: "Accounting", fr: "comptabilité" },
    accountingDetails: { pr: "میانگین قیمت خرید", en: "Average Purchase Price" },
    accountlimit: { pr: "تعداد صندوق", en: "Account Limit", fr: "nombres des caisse" },
    accountNumber: { pr: "شماره حساب", en: "Account Number", fr: "" },
    accountSummery: { pr: "خلاصه حساب", en: "Account Summery", fr: "estival compte" },
    accountType: { pr: "ماهیت حساب", en: "Account Type", fr: "type de compte" },
    acountReport: { pr: "گزارش حساب", en: "Account Report", fr: "compte" },
    acounts: { pr: "حساب ها", en: "Accounts", fr: "" },
    add: { pr: "اضافه", en: "Add" },
    addapplication: { pr: "جدید", en: "Add Application", fr: "ajouter l'application" },
    address: { pr: "آدرس", en: "Address", fr: "adresse" },
    addressPh: { pr: "آدرس....", en: "Address...", fr: "" },
    addSupplier: { pr: "ثبت تامین کننده", en: "Supplier Register", fr: "ajouter fournisseur" },
    addWithoutColorSize: { pr: " اضافه کردن بدون رنگ و جزئیات", en: "Add Without Color And Details", fr: "" },
    age: { pr: "سـن", en: "Age", fr: "âge" },
    ageFrom: { pr: "سن از", en: "Age From", fr: "" },
    allPurchase: { pr: "خرید کل", en: "Total Purchase", fr: "" },
    allSale: { pr: "فروش کل", en: "Total Sales", fr: "" },
    amount: { pr: "مبلغ", en: "Amount", fr: "montant" },
    amountFrom: { pr: "مبلغ از", en: "Amount From", fr: "quantité de" },
    amountOfCredit: { pr: "مبلغ اعتبار", en: "Credit Amount", fr: "" },
    amountSalary: { pr: "مبلغ حقوق", en: "Amount Salary", fr: "" },
    amountSalaryFrom: { pr: "مبلغ حقوق از:", en: "Amount Salary From", fr: "" },
    amountSum: { pr: "جمع مبلغ", en: "Total Amount", fr: "" },
    annual: { pr: "سالیانه", en: "Annual", fr: "" },
    Application: { pr: "برنامه", en: "Application" },
    applicationlist: { pr: "لیست برنامه ها", en: "Applications List", fr: "liste des applications" },
    applicationName: { pr: "نام برنامه", en: "Application Name" },
    applications: { pr: "برنامه ها", en: "Applications", fr: "applications" },
    appName: { pr: "نام برنامه", en: "Application Name", fr: "nom de l'application" },
    asType: { pr: "به روش :", en: "As Type :", fr: "le methode " },
    averageBuyPrice: { pr: "میانگین قیمت خرید بنا بر ارز مبدأ ", en: "Average Purchase Price By Index Currency" },
    averageSellPrice: { pr: "میانگین قیمت فروش", en: "Average Sale's Price", fr: "" },
    balance: { pr: "تراز مالی", en: "Balance", fr: "Solde financier" },
    balanceAmount: { pr: "باقیمانده", en: "Remaining", fr: "Solde du compte" },
    bank: { pr: "بانک", en: "Bank", fr: "banque" },
    bankList: { pr: "اسامی بانک ها", en: "Bank List", fr: "" },
    bankName: { pr: "نام بانک", en: "Bank Name", fr: "" },
    banks: { pr: "بانکها ", en: "Banks", fr: "banque" },
    barcode: { pr: "بارکد", en: "Barcode", fr: "code à barres" },
    base: { pr: "مبنا", en: "Index", fr: "" },
    basePrice: { pr: "قیمت پایه", en: "Base Price", fr: "Prix de base" },
    bestSellingItem: { pr: "کالاهای پرفروش", en: "Best Selling Goods", fr: "" },
    bottom: { pr: "پایین صفحه", en: "Bottom" },
    branch: { pr: "شعبه ", en: "Branch", fr: "branche" },
    branchCode: { pr: "کدشعبه", en: "Branch Code", fr: "" },
    branches: { pr: "شعب کاری", en: "Branches", fr: "branches" },
    branchManagement: { pr: "مدیریت شعب", en: "Branch Management", fr: "la gestion des branches" },
    branchName: { pr: "نام شعبه", en: "Branch Name", fr: "" },
    branchPricesWithAUser: { pr: "قیمت  شعبه به همراه یک کاربر اضافه", en: " Branch Prices With An Extra User", fr: "Prix de branche avec un utilisateur supplémentaire" },
    branchWithAUser: { pr: "شعبه به همراه یک کاربر اضافه", en: "Branch With An Extra User", fr: "Branche avec un utilisateur supplémentaire" },
    buy: { pr: "خرید", en: "Purchase", fr: "acheter" },
    buyAmount: { pr: "مبلغ خرید", en: "Buy Amount", fr: "montant de l'achat" },
    buyAmountOf: { pr: "مبلغ خرید از", en: "Buy Amount From", fr: "" },
    buyapplication: { pr: "خرید اشتراک", en: "Buy Membership", fr: "Acheter Adhésion" },
    buyChart: { pr: "نمودار خرید", en: "Purchase Chart" },
    buyer: { pr: "خریدار", en: "Buyer", fr: "" },
    buyerName: { pr: "نام خریدار", en: "Buyer Name", fr: "" },
    buyPrice: { pr: "قیمت خرید", en: "Buy Price", fr: "" },
    buyPriceFrom: { pr: "قیمت خرید از", en: "Buy Price From", fr: "" },
    by: { pr: "توسط", en: "By", fr: "" },
    byRemittance: { pr: "از طریق حواله", en: "By Remittance" },
    canAddBank: { pr: "مجاز به اضافه کردن بانک", en: "Autorized To Add Bank" },
    canAddCategory: { pr: "مجاز به اضافه کردن گروه بندی", en: "Autorized To Add Category" },
    canAddColorNSize: { pr: "مجاز به اضافه کردن رنگ وجزئیات کالا", en: "CanAutorized To Add Color And Size" },
    canAddCounter: { pr: "مجاز به اضافه کردن صندوق", en: "Autorized To Add Counter", fr: "Autorisés à ajouter des fonds" },
    canAddCounterForEmployee: { pr: "مجاز به اضافه کردن صندوق به کارمند", en: "Autorized To Add Counter For Employee" },
    canAddCurrency: { pr: "مجاز به اضافه کردن ارز", en: "Autorized To Add Currency", fr: "Autorisé à ajouter monnaie" },
    canAddCustomer: { pr: "مجاز به ثبت مشتری جدید", en: "Autorized To Add Customer", fr: "Autorisé à Ajouter clientèle" },
    canAddEmployee: { pr: "مجاز به اضافه کردن کارمند", en: "Autorized To Add Employee", fr: "Autorisé à ajouter un employé" },
    canAddExpense: { pr: "مجاز به ثبت هزینه متفرقه جدید", en: "Autorized To Add Expense", fr: "Autorisé à ajouter des dépenses" },
    canAddImage: { pr: "مجاز به اضافه کردن عکس کالا", en: "Autorized To Add Image" },
    canAddPhoneCustomer: { pr: "مجاز به اضافه کردن تلفن", en: "Autorized To Add Customer Phone", fr: "Autorisé à Ajouter téléphonique des clients" },
    canAddPrice: { pr: "مجاز به اضافه کردن قیمت کالا", en: "Autorized To Add Price" },
    canAddProduct: { pr: "مجاز به اضافه کردن کالا", en: "Autorized To Add Product" },
    canAddProductCategory: { pr: "مجاز به اضافه کردن دسته بندی کالا", en: "Autorized To Add Product Category" },
    canAddProductSetting: { pr: "مجاز به اضافه کردن تنضیمات کالا", en: "Autorized To Add Product Setting" },
    canAddSalary: { pr: "مجاز به ثبت دستمزد کارمندها", en: "Autorized To Add Salary", fr: "Autorisé à Ajouter Salaire" },
    canAddShopForEmployee: { pr: "مجاز به اضافه کردن شعبه به کارمند", en: "Autorized To Add Shop For Employee", fr: "Autorisé à ajouter direction à employé affecté" },
    canAddSocialSecurity: { pr: "مجاز به ثبت هزینه بیمه کارمندها", en: "Autorized To Add Social Security", fr: "Autorisé à ajouter la Sécurité sociale" },
    canAddSupplier: { pr: "مجاز به اضافه کردن تهیه کننده", en: "Autorized To Add Supplier" },
    canCancelOnlineOrder: { pr: "مجاز به بازگردانی وجه پرداخت آنلاین", en: "Autorized to refund online payments" },
    cancelOrder: { pr: "لغو سفارش", en: "Cancel Order" },
    canChangePassword: { pr: "مجاز به تغییر رمز عبور", en: "Autorized To Change Password", fr: "Autorisé à changer de mot de passe." },
    canChangeRole: { pr: "مجاز به ویرایش نقش ها", en: "Autorized To Change Role", fr: "Autorisé à modifier les rôles" },
    canConfirmExpense: { pr: "مجاز به تایید هزینه های متفرقه ثبت شده", en: "Autorized To Confirm Expense", fr: "Autorisé à confirmer dépenses" },
    canConfirmOnlineOrder: { pr: "مجاز به تایید فاکتور آنلاین", en: "Autorized to confirm online invoice" },
    canConfirmOrder: { pr: "مجاز به تایید سفارش های ثبت شده", en: "Autorized To Confirm Order", fr: "Autorisé à confirmer l'ordre" },
    canConfirmSalary: { pr: "مجاز به تاییددستمزدهای ثبت شده", en: "Autorized To Confirm Salary", fr: "Autorisé à confirmer Salaire" },
    canConfirmSocialSecurity: { pr: "مجاز به تایید هزینه بیمه کارمندهای ثبت شده", en: "Autorized To Confirm Social Security", fr: "Autorisé à confirmer la sécurité sociale" },
    canConfirmTransferMoney: { pr: "مجاز به تایید انتقال پول", en: "Autorized To Confirm Transfer Money", fr: "Autorisé à approuver le transfert d'argent" },
    canConfirmTransferProduct: { pr: "مجاز به تایید انتقال کالا", en: "Autorized To Confirm Transfer Product" },
    candDeleteCounter: { pr: "مجاز به حذف کردن صندوق", en: "Autorized To Delete Counter", fr: "Autorisé à supprimer des fonds" },
    canDeleteCategory: { pr: "مجاز به حذف کردن گروه بندی", en: "Autorized To Delete Category" },
    canDeleteColorNSize: { pr: "مجاز به حذف کردن رنگ و جزئیات کالا", en: "Autorized To Delete Color And Size" },
    canDeleteConfirmedExpense: { pr: "مجاز به حذف هزینه های متفرقه تایید شده", en: "Autorized To Delete Confirmed Expense", fr: "Autorisé à supprimer frais Confirmé" },
    canDeleteConfirmedSalary: { pr: "مجاز به حذف هزینه دستمزد تایید شده", en: "Autorized To Delete Confirmed Salary", fr: "Autorisé à supprimer Salaire Confirmé" },
    canDeleteConfirmedSocialSecurity: { pr: "مجاز به حذف هزینه بیمه تایید شده", en: "Autorized To Delete Confirmed Social Security", fr: "Peut supprimer la sécurité sociale Confirmé" },
    canDeleteConfirmedTransferedMoney: { pr: "مجاز به حذف انتقال پول تایید شده", en: "Autorized To Delete Confirmed Transfered Money", fr: "Autorisé à supprimer Confirmé argent Viré" },
    canDeleteConfirmedTransferedProducts: { pr: "مجاز به حذف کردن انتقال کالای تایید شده", en: "Autorized To Delete Confirmed Transfered Products" },
    canDeleteCounter: { pr: "مجاز به حذف صندوق", en: "Autorized to delete counter" },
    canDeleteCounterForEmployee: { pr: "مجاز به حذف کردن صندوق کارمند", en: "Autorized To Delete Counter For Employee" },
    canDeleteEmployee: { pr: "مجاز به حذف کردن کارمند", en: "Autorized To Delete Employee", fr: "Autorisé à supprimer un employé" },
    canDeleteImage: { pr: "مجاز به حذف کردن عکس کالا", en: "Autorized To Delete Image" },
    canDeleteOnlineOrder: { pr: "مجاز به حذف فاکتور آنلاین", en: "Autorized to delete online orders" },
    canDeletePhoneCustomer: { pr: "مجاز به حذف کردن تلفن", en: "Autorized To Delete Customer Phone", fr: "Autorisé à supprimer téléphonique des clients" },
    canDeletePrice: { pr: "مجاز به حذف کردن قیمت کالا", en: "Autorized To Delete Price" },
    canDeleteProduct: { pr: "مجاز به حذف کردن کالا", en: "Autorized To Delete Product" },
    canDeleteProductCategory: { pr: "مجاز به حذف کردن دسته بندی کالا", en: "Autorized To Delete Product Category" },
    canDeleteProductSetting: { pr: "مجاز به حذف کردن تنضیمات کالا", en: "Autorized To Delete Product Setting" },
    canDeleteSale: { pr: "مجاز به حذف کردن فروش", en: "Autorized To Delete Sale", fr: "Autorisé à supprimer vente" },
    canDeleteShopForEmployee: { pr: "مجاز به حذف کردن شعبه کارمند", en: "Autorized To Delete Shop For Employee" },
    canDeposit: { pr: "مجاز به واریز به صندوق", en: "Autorized To Deposit", fr: "Autorisé à déposer" },
    canEditAddress: { pr: "مجاز به ویرایش آدرس", en: "Autorized To Modify Address", fr: "Autorisé à modifier Adresse" },
    canEditAllCustomers: { pr: "مجاز به ویرایش همه مشتری ها", en: "Autorized To Modify All Customers", fr: "Autorisé à modifier tous les clients" },
    canEditAllSuppliers: { pr: "مجاز به ویرایش همه تهیه کننده ها", en: "Autorized To Modify All Suppliers" },
    canEditApplication: { pr: "مجاز به ویرایش برنامه", en: "Autorized To Modify Application" },
    canEditCategory: { pr: "مجاز به ویرایش دسته بندی کالا", en: "Autorized To Modify Category" },
    canEditConfirmedExpense: { pr: "مجاز به ویرایش هزینه متفرقه تایید شده", en: "Autorized To Modify Confirmed Expense", fr: "Autorisé à modifier dépenses Confirmé" },
    canEditCounter: { pr: "مجاز به ویرایش کردن صندوق", en: "Autorized To Modify Counter", fr: "Autorisés à modifier des fonds" },
    canEditCurrencyRate: { pr: "مجاز به ویرایش کردن نرخ ارز", en: "Autorized To Modify Currency Rate", fr: "autorisé à modifier le taux de change" },
    canEditCustomer: { pr: "مجاز به ویرایش مشتری", en: "Autorized To Modify Customer", fr: "Autorisé à modifier clientèle" },
    canEditCustomerAddress: { pr: "مجاز به ویرایش آدرس مشتری", en: "Autorized To Modify Customer Address", fr: "Autorisé à modifier Adresse du client" },
    canEditCustomerRoles: { pr: "مجاز به ویرایش دسترسی مشتری", en: "Autorized to modify customer access" },
    canEditEmployee: { pr: "مجاز به ویرایش کردن کارمند", en: "Autorized To Modify Employee", fr: "Autorisé à éditer un employé" },
    canEditExpenseCategory: { pr: "مجاز به ویرایش گروه هزینه های متفرقه", en: "Autorized To Modify Expense Category", fr: "Autorisé à modifier Catégorie de dépenses" },
    canEditHelp: { pr: "مجاز به ویرایش کردن راهنما", en: "Autorized To Modify Help" },
    canEditItemDetail: { pr: "مجاز به ویرایش مشخصات کالا", en: "Autorized To Modify Item Detail" },
    canEditItemProperty: { pr: "مجاز به ویرایش مشخصات پویای کالا", en: "Autorized To Modify Item Dynamic Property" },
    canEditMeasureUnit: { pr: "مجاز به ویرایش واحد کالا", en: "Autorized To Modify Measure Unit" },
    canEditOnlineMenu: { pr: "مجاز به ویرایش منوی فروشگاه آنلاین", en: "Autorized to modify online store menu" },
    canEditPayment: { pr: "مجاز به ویرایش واریز / برداشت", en: "Autorized To Modify Payment", fr: "Autorisé à modifier paiement" },
    canEditProperty: { pr: "مجاز به ویرایش مشخصات پویا", en: "Autorized To Modify Property" },
    canEditQuantity: { pr: "مجاز به ویرایش تعداد کالا", en: "Autorized To Modify Quantity" },
    canEditSale: { pr: "مجاز به ویرایش فروش", en: "Autorized To Modify Sale", fr: "Autorisé à modifier vente" },
    canEditSetting: { pr: "مجاز به ویرایش تنظیمات", en: "Autorized to modify setting" },
    canEditShop: { pr: "مجاز به ویرایش کردن شعبه فروشگاه", en: "Autorized To Modify Store" },
    canEditSmsSubject: { pr: "مجاز به ویرایش کردن موضوع پیامک", en: "Autorized To Modify Sms Subject" },
    canEditSupplier: { pr: "مجاز به ویرایش کردن تهیه کننده هایی که تعریف کرده است", en: "Autorized To Modify Supplier" },
    canEditVoucher: { pr: "مجاز به ویرایش کارت هدیه", en: "Autorized To Modify Voucher", fr: "Autorisé à modifier Voucher" },
    canGetCredit: { pr: "مجاز به خرید نسیه", en: "Can Purchase By Credit" },
    canGiveCredit: { pr: "مجاز به نسیه دادن", en: "Autorized To Give Credit", fr: "Autorisé à donner le crédit" },
    canGiveDiscount: { pr: "مجاز به تخفیف دادن", en: "Autorized To Give Discount", fr: "Autorisé à donner l'escompte" },
    canIssueVoucher: { pr: "مجاز به صدور کارت هدیه", en: "Autorized To Issue Voucher", fr: "Autorisé à émettre des chèques" },
    canMakeReturn: { pr: "مجاز به عودت دادن", en: "Autorized To Make Return", fr: "Autorisé à rendre le retour" },
    canReceiveByCheque: { pr: "مجاز به واریز چک", en: "Autorized To Receive By Cheque", fr: "Peuvent recevoir par chèque" },
    canReceiveByVoucher: { pr: "مجاز به واریز کارت هدیه", en: "Autorized To Receive By Voucher", fr: "Autorisé à recevoir par chèque" },
    canSale: { pr: "مجاز به فروش", en: "Autorized To Sale", fr: "Autorisé à vendre" },
    canSeeAllAccount: { pr: "مجاز به دیدن تمام ریزحساب ها", en: "Autorized To See All Account", fr: "Autorisé à voir tous les comptes" },
    canSeeAllBuy: { pr: "مجاز به مشاهده همه ی فاکتورهای خرید", en: "Autorized To See All Buy" },
    canSeeAllCustomers: { pr: "مجاز به مشاهده همه مشتری ها", en: "Autorized To See All Customers", fr: "Autorisé à voir tous Les clients" },
    canSeeAllPaymentes: { pr: "مجاز به دیدن تمام واریز / برداشت ها", en: "Autorized To See All Payments", fr: "Autorisé à voir tous les paiements" },
    canSeeAllSales: { pr: "مجاز به دیدن تمام فروش ها", en: "Autorized To See All Sales", fr: "Autorisé à voir toutes les ventes" },
    canSeeAllSupplierPayments: { pr: "مجاز به مشاهده واریز/برداشت همه تهیه کننده ها", en: "Autorized To See All Supplier Payments" },
    canSeeAllSuppliers: { pr: "مجاز به مشاهده همه ی تهیه کننده ها", en: "Autorized To See All Suppliers" },
    canSeeItemReport: { pr: "مجاز به مشاهده آمار کالا", en: "Autorized To See Item Report" },
    canSeeSellChart: { pr: "مجاز به مشاهده نمودار فروش", en: "Autorized To See Sell Chart", fr: "Autorisé à voir Tableau Vendre" },
    canSendSMS: { pr: "مجاز به ارسال پیامک به مشتری هایی که ثبت کرده است", en: "Autorized To Send Sms" },
    canSendSmsToAll: { pr: "مجاز به ارسال پیامک به همه ی مشتری ها", en: "Autorized To Send Sms To All" },
    canTransferMoney: { pr: "مجاز به انتقال دادن پول", en: "Autorized To Transfer Money", fr: "Autorisé à transférer de l'argent" },
    canTransferProduct: { pr: "مجاز به انتقال کالا", en: "Autorized To Transfer Product" },
    canWithdraw: { pr: "مجاز به برداشت از حساب", en: "Autorized To Withdraw", fr: "Autorisé à retirer" },
    cardNo: { pr: "شماره کارت", en: "Card Number", fr: "" },
    cardValueOf: { pr: " ارزش کارت از", en: "Card Value From", fr: "" },
    cash: { pr: "نقدی", en: "Cash", fr: "espèces" },
    cashier: { pr: "صـندوق", en: "Cashier", fr: "caissier" },
    cashierBalance: { pr: "موجودی صندوق", en: "Counter Balance", fr: "équilibre caissière" },
    cashierCode: { pr: "کد صندوق", en: "Counter Code", fr: "" },
    cashierManagement: { pr: "مدیریت صندوق", en: "Cashiers Management", fr: "caissiers de gestion" },
    cashiers: { pr: "صـندوق ها", en: "Cashiers", fr: "caissiers" },
    cashPay: { pr: "برداشت نقدی", en: "Cash Pay", fr: "espèces" },
    cashPayChequePay: { pr: "برداشت نقدی و چک", en: "Cash And Cheque Deposits", fr: "Payer en espèces et en chèque " },
    cashReceive: { pr: "واریز نقدی", en: "cash deposit", fr: "En espèces" },
    cashReceiveChequeReceive: { pr: "واریز چک و نقدی", en: "Cash And Cheque Withdrawal", fr: "reçues en espèces et en chèque" },
    category: { pr: "دسته بندی", en: "Category", fr: "catégorie" },
    cellPhone: { pr: "موبایل", en: "Mobile" },
    certificateNumber: { pr: "کد ملی", en: "Certification Number", fr: "" },
    changeEmail: { pr: "تغییر ایمیل", en: "Change Email", fr: "" },
    character: { pr: "کاراکتر", en: "Character", fr: "" },
    chart: { pr: "نمودار", en: "Chart" },
    check: { pr: "بررسی", en: "Check" },
    chengePassword: { pr: "تغییر رمزعبور", en: "Change Password", fr: "" },
    cheque: { pr: "چک", en: "Cheque", fr: "chèque" },
    chequeAmount: { pr: "مبلغ چک", en: "Cheque Amount", fr: "montant du chèque" },
    chequeDate: { pr: "ناریخ چک روز/ماه/سال", en: "Cheque Date dd/mm/yyyy", fr: "date qui passe chèque dd/mm/yyyy" },
    chequeError: { pr: "اطلاعات چک را کامل وارد کنید.", en: "Enter complete information of Cheque", fr: "Entrez les informations complètes sur le chèque." },
    chequeMaturityDateOf: { pr: "تاریخ سررسید چک از", en: "Cheque Due Date From", fr: "" },
    chequePay: { pr: "برداشت چک", en: "Cheque Pay", fr: "par chèque" },
    chequeReceive: { pr: "واریز چک", en: "Cheque deposit", fr: "Faites chèque" },
    chequeSerial: { pr: "سریال چک", en: "Cheque Serial", fr: "série chèque" },
    choose: { pr: "انتخاب کنید", en: "select", fr: "" },
    chooseFile: { pr: "انتخاب فایل", en: "Choose File" },
    chooseGender: { pr: "جنسیت را انتخاب کنید", en: "Select Gender", fr: "" },
    chooseTime: { pr: "انتخاب مدت", en: "Select Time", fr: "" },
    code: { pr: "کد", en: "Code", fr: "" },
    color: { pr: "رنگ", en: "Color", fr: "couleur" },
    colorIsEmpty: { pr: "رنگ را انتخاب کنید.", en: "Choose the color", fr: "Choisissez de la couleur" },
    colorName: { pr: "نام رنگ", en: "Color Name", fr: "" },
    colorSizeList: { pr: "لیست رنگ و جزئیات", en: "Color & Size List", fr: "liste des colours et la taille" },
    colorSizeQuantity: { pr: "رنگ، جزئیات و تعداد", en: "Color,Details And Quantity", fr: "" },
    commission: { pr: "پورسانت", en: "Commission", fr: "commission" },
    confirm: { pr: "تائید", en: "Confirm", fr: "confirmer" },
    confirmed: { pr: "تایید شده", en: "Confirmed", fr: "confirmé" },
    confirmer: { pr: "تایید کننده", en: "Confirmer", fr: "" },
    confirmerCode: { pr: "کد تایید کننده", en: "Confirmer Code", fr: "confirmateur de code" },
    confirmNewPassword: { pr: "تکرار رمزعبور جدید", en: "Confirm", fr: "" },
    confirmOrder: { pr: "تایید فاکتور", en: "Confirm Orders" },
    confirmPassword: { pr: "تکرار رمز", en: "Confirm ", fr: "" },
    confirmSell: { pr: "تایید سفارش", en: "sales Confirmation" },
    contactNumber: { pr: "شماره تماس", en: "Contact Number", fr: "" },
    cost: { pr: "ارزش", en: "Cost", fr: "coût" },
    count: { pr: "تعداد", en: "Quantity", fr: "nombre" },
    counter: { pr: "صندوق", en: "Counter", fr: "caisse" },
    counterPayment: { pr: "واریز/برداشت صندوق", en: "Counter Diposite/Withdrawal", fr: "paiement compte" },
    countFrom: { pr: "تعداد از", en: "Quantity From", fr: "" },
    creditCard: { pr: "کارت", en: "Credit Card", fr: "carte de crédit" },
    creditor: { pr: "بستانکار", en: "Creditor", fr: "créancier" },
    creditorship: { pr: "بستانکاری", en: "Creditorship", fr: "" },
    crm: { pr: "ارتباط با مشتری", en: "CRM" },
    currencies: { pr: "ارزها", en: "Currencies", fr: "devises" },
    Currency: { pr: "ارز", en: "Currency", fr: "monnaie" },
    currencyNames: { pr: "نام ارز", en: "Currency Names", fr: "nom de la monnaie" },
    currencyRate: { pr: "نرخ ارز", en: "Currency Rate", fr: "cours des devises" },
    currencySign: { pr: "نشان ارز", en: "Currency Symbol", fr: "" },
    current: { pr: "تومان", en: "USD", fr: "euro" },
    customer: { pr: "مشـتری", en: "Customer", fr: "client" },
    customerAcountReport: { pr: "گزارش حساب مشتری", en: "customer Account Report", fr: "Compte  de client" },
    customerCode: { pr: "کد مشتری", en: "Customer Code", fr: "" },
    customerNameFamily: { pr: "نـام و نـام خانوادگی مشتری ", en: "Customer Name And Family Name", fr: "" },
    customers: { pr: "مشـتری ها", en: "Customers", fr: "clients" },
    customerSpender: { pr: "مشتری(خرج کننده)", en: "Customer(Spender)", fr: "" },
    daily: { pr: "روزانه", en: "Daily", fr: "" },
    dailySellingAverage: { pr: "میانگین فروش روزانه", en: "Daily Selling Average", fr: "" },
    dashboard: { pr: "داشبورد", en: "Dashboard" },
    date: { pr: "تاریخ", en: "Date", fr: "le date" },
    dateOfBirth: { pr: " تاریخ تولد", en: "Date Of Birth", fr: "" },
    dateOfEmployment: { pr: "تاربخ استخدام", en: "Date Of Employment", fr: "" },
    dateOfRegistration: { pr: "تاریخ ثبت نام", en: "Date Of Registration", fr: "" },
    dateOfRegistrationFrom: { pr: "تاریخ ثبت نام از", en: "Date of Registration From", fr: "" },
    dateSaveFrom: { pr: "تاریخ ثبت از", en: "Save Date From", fr: "jour sauver de" },
    dateStart: { pr: "تاریخ شروع", en: "Start Date", fr: "date de début" },
    daY: { pr: "1روز ", en: "1Day", fr: "" },
    dayFourteen: { pr: "14 روز", en: "14Days", fr: "" },
    daySeven: { pr: "7 روز", en: "7Days", fr: "" },
    dayThirty: { pr: "30 روز", en: "30Days", fr: "" },
    debt: { pr: "بدهی", en: "Debt", fr: "" },
    debtOf: { pr: "بدهی از", en: "Debt From", fr: "" },
    debtor: { pr: "بدهکار", en: "Debtor", fr: "débiteur" },
    debtPrice: { pr: "مبلغ بدهی", en: "Debt Amount", fr: "" },
    debtSum: { pr: "جمع بدهی", en: "Total debt", fr: "" },
    deleteBtn: { pr: "حذف", en: "Delete", fr: "supprimer" },
    deleteKey: { pr: "حذف", en: "Delete", fr: "" },
    deliveryExpense: { pr: "هزینه پیک", en: "Delivery Expense" },
    demolishedItem: { pr: "اجناس خراب", en: "Broken Goods", fr: "" },
    description: { pr: "توضیحات", en: "Description", fr: "description" },
    details: { pr: "جزئیات", en: "Details", fr: "détail" },
    differentPass: { pr: "رمز عبور و تکرار آن یکسان نیست.", en: "the password and confirm are not the same!", fr: "le mot de passe et confirmer ne sont pas la même chose!" },
    discountAmount: { pr: "تخفیف", en: "Discount Amount" },
    discountPercent: { pr: "درصد تخفیف", en: "Discount Percent", fr: "" },
    discountSum: { pr: "جمع تخفیف", en: "Total Discount", fr: "" },
    downUp: { pr: "پایین به بالا", en: "Bottom-up", fr: "" },
    drop: { pr: "کم", en: "Drop" },
    edit: { pr: "ویرایش", en: "Edit", fr: "edition" },
    editAddress: { pr: "ویرایش آدرس", en: "Edit Address", fr: "modifier l'adress" },
    editapplication: { pr: "ویرایش برنامه", en: "Edit Application", fr: "modifier l'application" },
    editapplicationroles: { pr: "ویرایش نقش های مدیر", en: "Modify Admin Roles", fr: "modifier le rôle d'administrateur" },
    editPhone: { pr: "ویرایش تلفن", en: "Edit Phones", fr: "modifier le téléphone" },
    email: { pr: "ایمیل", en: "Email" },
    emailPass: { pr: "رمز عبور ایمیل", en: "Email Password" },
    emoloyeelimit: { pr: "تعداد کارمند", en: "Employee Limit", fr: "nombres des employes" },
    employee: { pr: "کارمند", en: "Employee", fr: "employé" },
    employeeCode: { pr: "کـد کارمند", en: "Employee Code", fr: "code de l'employé" },
    employeeManagement: { pr: "مدیریت کارمند", en: "Employee Management", fr: "la gestion du personnel" },
    employeeName: { pr: "نام کارمند", en: "Employee Name", fr: "nom de l'employé" },
    employeeNamefamily: { pr: "نـام و نـام خانوادگی کارمند", en: "Employee Name And Family", fr: "nom et la famille de l'employé" },
    employeeRcv: { pr: "کارمند(دریافت کننده)", en: "Employee(Reciever)", fr: "" },
    employees: { pr: "کارمندها", en: "Employees", fr: "employés" },
    error: { pr: "خطا در انجام عمملیات.", en: "ERROR!", fr: "erreur!" },
    example: { pr: "مثال: ", en: "Example", fr: "" },
    exist: { pr: "این نام کاربری قبلا ثبت شده است، نام کاربری را تغییر دهید.", en: "This username is already registered,try another. ", fr: "Ce nom d'utilisateur est déjà enregistré, changez le nom d'utilisateur" },
    existQuantity: { pr: "تعداد موجود", en: "Availibility Quantity", fr: "" },
    exit: { pr: "خروج", en: "Exit" },
    expense: { pr: "هزینه", en: "Expense", fr: "frais" },
    expenseGrp: { pr: "گروه هزینه", en: "Expense Group", fr: "groupe de charge" },
    expenses: { pr: "هزینه ها", en: "Expenses", fr: "dépenses" },
    expieryDate: { pr: "تاریخ اعتبار از", en: "Expiery Date From", fr: "" },
    expieryDate: { pr: "تاریخ انقضاء", en: "Expiery Date" },
    expressOrder: { pr: "ثبت فاکتور", en: "Express Order", fr: "s'inscrire facture" },
    extraEmployeePrice: { pr: "قیمت کارمند اضافه", en: "Extra Employee Price", fr: "Prix des employés supplémentaire" },
    extraUser: { pr: "کاربر  اضافه", en: "Extra User", fr: "utilisateur supplémentaire" },
    FailedToMobile: { pr: "ارسال نشد.", en: "Sms Failed!" },
    family: { pr: "نام خانوادگی", en: "Family Name", fr: "nom de famille" },
    faq: { pr: "سئوالات متداول", en: "FAQ" },
    fax: { pr: "فاکس", en: "Fax", fr: "" },
    features: { pr: "امکانات", en: "Features" },
    female: { pr: "زن", en: "Female", fr: "" },
    finalCount: { pr: "تعداد نهایی", en: "Final Count", fr: "les nombres final" },
    finalPrice: { pr: "قیمت نهایی", en: "Final Price", fr: "prix final" },
    fixSalary: { pr: "حقوق ثابت", en: "Fix Salary", fr: "salaire fixe" },
    forExpense: { pr: "بابت هزینه", en: "For Expense", fr: " en frais" },
    forSalary: { pr: "بابت حقوق", en: "For Salary", fr: "en salaire" },
    forSocialSecurity: { pr: "بابت بیمه", en: "For Socialsecurity", fr: "pour l'assurance" },
    forwardPurchasing: { pr: "پیش خرید", en: "advance Purchase", fr: "Anticipée" },
    freinds: { pr: "دوستان", en: "Friends" },
    friendPrice: { pr: "قیمت دوستان", en: "Friends Price", fr: "" },
    fromBranch: { pr: "شعبه مبدا", en: "Origin Branch", fr: "" },
    fromCounter: { pr: "صندوق مبدا", en: "Origin Counter", fr: "" },
    fromDate: { pr: "از تاریخ", en: "From Date", fr: "sur(la date)" },
    fullAccountReport: { pr: "فروشگاه", en: "Store", fr: "magasin" },
    fullAddress: { pr: "آدرس کامل", en: "Full Address" },
    gender: { pr: "جنسیت", en: "Gender", fr: "sexe" },
    giftNote: { pr: "متن کارت هدیه", en: "Gift Note" },
    group: { pr: "گروه", en: "Group", fr: "" },
    help: { pr: "راهنما", en: "Help", fr: "Guide" },
    host: { pr: "هاست ایمیل", en: "Email Host" },
    ifYouWantToChangeYourEmailPleaseFillTheseInformation: { pr: "   اگر مایلید که ایمیل خود را تغییر دهید،لطفا اطلاعات زیر را تکمیل فرمایید", en: "If you wish to change your email,Please fill the following informations.", fr: "" },
    ifYouWantToChangeYourPersonalAccountPasswordPleaseFillTheseInformation: { pr: "اگرمایلید که رمزعبور حساب شخصی خود را تغییر دهید،لطفا اطلاعات زیر را تکمیل فرمایید", en: "If you wish to change your personal Account password,Please fill the following informations.", fr: "" },
    image: { pr: "عکس", en: "Image", fr: "" },
    include: { pr: "شامل", en: "Include", fr: "" },
    incomeSummery: { pr: "گزارش درآمد ", en: "Income Summery", fr: "estivale revenu" },
    indeptedness: { pr: "بدهکاری", en: "Indeptedness", fr: "" },
    introducedBuyingOf: { pr: " خرید معرفی شده از", en: "Introduced Buy From", fr: "" },
    introducer: { pr: " معرف", en: "Introducer", fr: "" },
    introducerCode: { pr: "کد معرف", en: "Introducer Code", fr: "Code introducteur" },
    invalid: { pr: "نامعتبر", en: "Invalid", fr: "" },
    inventory: { pr: "کالا و انبار", en: "Inventory", fr: "inventaire" },
    Inventory: { pr: "انبارداری", en: "Inventory", fr: "inventaire" },
    inventory1: { pr: "کالا", en: "Item", fr: "marchandise" },
    invoiceList: { pr: "لیست فاکتورها", en: "Invoices List" },
    invoiceNumber: { pr: "شماره فاکتور", en: "InvoiceNo", fr: "numéro de facture" },
    isactive: { pr: "فعال", en: "Active", fr: "actif" },
    isGift: { pr: "هدیه است.", en: "Is Gift" },
    isLink: { pr: "لینک است", en: "Is Link" },
    isShow: { pr: "نمایش دهد", en: "show", fr: "" },
    issueDate: { pr: "تاریخ صدور", en: "Issue Date", fr: "" },
    issueDateFrom: { pr: "تاریخ صدور از", en: "Issue Date From", fr: "" },
    issuedEmployee: { pr: "کارمند صادر کننده", en: "Issuer Employee", fr: "" },
    issueInvoiceDateOf: { pr: "تاریخ صدور فاکتور از", en: "Issue Invoice Date From", fr: "" },
    item: { pr: "کالا", en: "Item", fr: "" },
    itemAmount: { pr: "مبلغ کالا", en: "Item Amount", fr: "" },
    itemBarcode: { pr: "بارکد کالا", en: "Item Barcode", fr: "" },
    itemCategory: { pr: "گروه بندی", en: "Item Categories", fr: "marchandise catégorie" },
    itemCode: { pr: "کد کالا", en: "Item Code", fr: "code de produit" },
    itemCodeAndName: { pr: "نام و کد کالا", en: "Item Name And Code", fr: "nom et le code du produit" },
    itemCodeOrName: { pr: "نام یا کد کالا", en: "Item Name Or Code", fr: "nom ou le code du produit" },
    itemDefinition: { pr: "توضیحات", en: "Item Description" },
    itemImages: { pr: "عکس کالا", en: "Item Images", fr: "l'image des produits de base" },
    itemManagement: { pr: "مدیریت کالا", en: "Item Management", fr: "gestion des produits" },
    itemMatchingBarcode: { pr: "کالاهای مشابه", en: "Matching Products" },
    itemName: { pr: "نام کالا", en: "Item Name", fr: "le nom du produit" },
    itemPriceAverage: { pr: "میانگین قیمت کالا", en: "Item Price Average", fr: "" },
    itemProperty: { pr: "مشخصات کالا", en: "Item Property", fr: "la propriété de produit" },
    itemQuantity: { pr: "تعداد کالا	", en: "Item Quantity", fr: "" },
    items: { pr: "کالاها", en: "Goods", fr: "" },
    itemsPerPage10: { pr: "10 ردیف در هر صفحه", en: "10 Rows In Each Page", fr: "10 lignes par page" },
    itemsPerPage20: { pr: "20 ردیف در هر صفحه", en: "20 Rows In Each Page", fr: "20 lignes par page" },
    itemsPerPage40: { pr: "40 ردیف در هر صفحه", en: "40 Rows In Each Page", fr: "40 lignes par page" },
    itemsPerPage5: { pr: "5 ردیف در هر صفحه", en: "5 Rows In Each Page", fr: "5 lignes par page" },
    itemStatus: { pr: "وضعیت کالا", en: "Item Status", fr: "nom ou le code du produit" },
    itemStock: { pr: "موجودی کالا", en: "Items Stock", fr: "marchandise de stock" },
    itemTransfer: { pr: "انتقال کالا", en: "Transfer Item", fr: "marchandise transfert" },
    itemTransferHistory: { pr: " سوابق انتقال کالا", en: "Transfered Items History", fr: "historique des transferts des produit de base" },
    itemUnit: { pr: "واحد کالا", en: "Item Unit", fr: "" },
    itemWeight: { pr: "وزن کالا", en: "Item Weight", fr: "" },
    job: { pr: "شغل", en: "Job", fr: "" },
    job: { pr: "شغل", en: "Job", fr: "emploi" },
    kardex: { pr: "کاردکس کالا", en: "Item Kardex", fr: "kardex" },
    language: { pr: "زبان", en: "Language" },
    lastMessageDateFrom: { pr: "تاریخ آخرین پیام از", en: "Last Message Date From", fr: "" },
    lastPaymentDateFrom: { pr: " تاریخ آخرین پرداخت از", en: "Late Payment Date From", fr: "" },
    lastPurchaseOf: { pr: "آخرین خرید از", en: "Last Purchase From", fr: "" },
    linkTo: { pr: "لینک به سایت", en: "Link To" },
    mainBranch: { pr: "شعبه اصلی", en: "Main Branch", fr: "" },
    mainPassword: { pr: "رمزعبور اصلی", en: "Main Password", fr: "" },
    mainPrice: { pr: "قیمت اصلی", en: "Main Price", fr: "" },
    male: { pr: "مرد", en: "Male", fr: "" },
    manager: { pr: "مدیر", en: "Manager", fr: "" },
    matchingBarcode: { pr: "کالای مشابه", en: "Matching Product" },
    matchingItems: { pr: "کالاهای مشابه", en: "Matching Items", fr: "correspondant à des produits de base" },
    measureUnit: { pr: "واحد شمارش", en: "Measure Unit", fr: "unité de compte" },
    menuLocation: { pr: "موقعیت منو", en: "Menu Position" },
    menuPhotos: { pr: "تصاویر منو", en: "Menu Photos" },
    message: { pr: "پیغام", en: "Message", fr: "" },
    messages: { pr: " پیامکها", en: "Messages", fr: "messages" },
    mobile: { pr: " شماره موبایل", en: "Mobile", fr: "mobile" },
    mobileExample: { pr: "مثال موبایل", en: "Mobile Example", fr: "" },
    moneyTransfer: { pr: "انتقال پـول", en: "Money Transfer", fr: "transfert d'argent" },
    montH: { pr: "1 ماه", en: "1Months", fr: "" },
    month: { pr: "ماه", en: "Month", fr: "mois" },
    monthly: { pr: "ماهانه", en: "Monthly", fr: "" },
    monthSix: { pr: "6 ماه", en: "6Months", fr: "" },
    moreFilter: { pr: "جستجوی پیشرفته ", en: "More Filter Options", fr: "Recherche avancée" },
    name: { pr: "نام", en: "Name", fr: "prénom" },
    nameAndFamily: { pr: "نام و نام خانوادگی", en: "Name And Family", fr: "" },
    nameMenu: { pr: "نام منو", en: "Menu Name" },
    needWrap: { pr: "کادو شود", en: "Need Wrap" },
    netPaymentOf: { pr: "پرداخت خالص از", en: "Net Payment From", fr: "" },
    netPurchaseOf: { pr: " خرید خالص از", en: "Net Purchase From", fr: "" },
    netQuantity: { pr: "تعداد خالص", en: "Net Sold Quantity", fr: "" },
    netRecievedAmount: { pr: "مبلغ واریزی خالص", en: "Net Deposited Amount ", fr: "" },
    netSale: { pr: "فروش خالص", en: "Net Sale", fr: "" },
    newBranch: { pr: "جدید", en: "New Branch", fr: "nouvelle branche" },
    newCashier: { pr: "جدید", en: "New Cashier", fr: "nouveau caissier" },
    newColorSize: { pr: "رنگ و جزئیات جدید", en: "New Color & Size", fr: "nouvelle couleur et la taille" },
    newCustomer: { pr: "ثبت مشتری", en: "New Customer", fr: "nouveau client" },
    newEmployee: { pr: "جدید", en: "New Employee", fr: "nouvel employé " },
    newItem: { pr: "کالای جدید", en: "New Item", fr: "nouvelle marchandise" },
    newPassword: { pr: "رمزعبور جدید", en: "New Password", fr: "" },
    newSell: { pr: "فروش جدید", en: "New Sale", fr: "" },
    newStock: { pr: "موجودی جدید", en: "New Item", fr: "" },
    newVoucher: { pr: "کارت هدیه جدید", en: "New Voucher", fr: "nouvelle copoun" },
    next: { pr: "بعدی->>", en: "Next->>" },
    no: { pr: "خیر", en: "No" },
    noParent: { pr: "مشخصه انتخاب شده باید حتما زیرگره یک مشخصه کلی باشد.", en: "Property Don't Have Parent!" },
    notactive: { pr: "غیرفعال", en: "Not Active", fr: "inactif" },
    notAllowedByVoucher: { pr: "شما اجازه ثبت کارت هدیه را ندارید.", en: "You don't allowed to register the gift card.", fr: "vous n'avez pas le droit d'enregistrer la carte-cadeau" },
    notConfirmed: { pr: "تایید نشده", en: "Not Conirmed", fr: "pas confirmé" },
    notInRole: { pr: "شما مجاز به این کار نیستید.", en: "You dont have access.", fr: "Vous n'avez pas accès." },
    notPassedCheque: { pr: "چکهای پاس نشده", en: "Not Passed Cheque", fr: "pas passé chèque " },
    notpassedChequeOf: { pr: "چکهای پاس نشده از", en: "Not Passed Cheque From", fr: "" },
    notShow: { pr: "نمایش ندهد", en: "don't show", fr: "" },
    notValid: { pr: "مقدار معتبر وارد کنید", en: "This field is not valid!", fr: "ce champ n'est pas valide" },
    numbeofEmployees: { pr: "تعداد کارمند", en: " Number Of Employees", fr: "nombre d'employés" },
    number: { pr: "شماره", en: "Number", fr: "nombre" },
    numberOfBranches: { pr: "تعداد شعبه", en: "Number Of Branches", fr: "nombre de branches" },
    numberOfFunds: { pr: "تعداد صندوق", en: "Number Of Counter", fr: "nombre de fonds" },
    numberOfPages: { pr: "تعداد صفحه", en: "Number of Pages", fr: "" },
    numberOfSms: { pr: "تعداد پیامک", en: "Number Of Sms", fr: "nombre de SMS" },
    numberPerPage10: { pr: "10 تعداد در هر صفحه", en: "10 Number Per Page", fr: "" },
    numberPerPage20: { pr: "20 تعداد در هر صفحه", en: "20 Number Per Page", fr: "" },
    numberPerPage40: { pr: "40 تعداد در هر صفحه", en: "40 Number Per Page", fr: "" },
    numberPerPage5: { pr: "5 تعداد در هر صفحه", en: "5 Number Per Page", fr: "" },
    ok: { pr: "با موفقیت انجام شد.", en: "Done successfully.", fr: "fait avec succès." },
    Online: { pr: "آنلاین", en: "Online" },
    onlineCategoriesManagement: { pr: "مدیریت گروه محصولات", en: "Product Category Management" },
    onlineCounter: { pr: "شعبه آنلاین", en: "Online Branch" },
    onlineEmployee: { pr: "کارمند آنلاین", en: "Online Employee" },
    onlineLogo: { pr: "لوگوی فروشگاه آنلاین", en: "Online Store Logo" },
    onlineMenu: { pr: "منوهای فروشگاه آنلاین", en: "Online Store Menus" },
    onlinePrice: { pr: "قیمت آنلاین", en: "Online Price", fr: "" },
    onlineProfile: { pr: "تنظیمات دسترسی", en: "accessibility Setting" },
    onlineShow: { pr: "نمایش آنلاین", en: "online show", fr: "" },
    onlineSliderShow: { pr: "اسلایدر آنلاین", en: "Online Slider Show" },
    onlineStore: { pr: "فروشگاه آنلاین", en: "Online Store" },
    onReceive: { pr: "پرداخت به پیک", en: "On Receive" },
    order: { pr: "سفارش", en: "Order", fr: "" },
    order: { pr: "فاکتور", en: "Order", fr: "facture" },
    orderHistory: { pr: "ریز حساب", en: "Account Details", fr: "l'histoire de commande" },
    ordering: { pr: "ترتیب", en: "Order", fr: "" },
    orderProfit: { pr: "سود فاکتورها", en: "Orders Profit" },
    orders: { pr: "سفارشات", en: "Order", fr: "ordres" },
    originalQuantity: { pr: " تعداد کالای اصلی", en: "Main Item Quantity", fr: "" },
    otherExpenses: { pr: "هزینه های متفرقه ", en: "Other Expenses", fr: "autres dépenses" },
    page: { pr: "صفحه", en: "Page", fr: "" },
    paidForExpense: { pr: "بابت هزینه متفرقه", en: "For Miscellaneous Expense" },
    paidForSocialSecurity: { pr: "بابت هزینه بیمه", en: "For Socialsecurity Expenses" },
    partedItemUnit: { pr: "جزئی ترین واحد کالا", en: "Detailed Unit", fr: "" },
    passedCheque: { pr: "چکهای پاس شده", en: "Passed Cheque", fr: "passé chèque" },
    passedChequeOf: { pr: "چک های پاس شده از", en: "Passed Cheque From", fr: "" },
    password: { pr: "کلمه عبور", en: "password", fr: "moi de passer" },
    payAmount: { pr: "مبلغ برداشت شده", en: "Pay Amount", fr: "compte payé" },
    payed: { pr: "پرداختی", en: "Payed Amount", fr: "" },
    payedAmount: { pr: "مبلغ پرداخت شده", en: "Payed Amount", fr: "" },
    payment: { pr: "واریز/برداشت", en: "Deposite/Withdrawal", fr: "" },
    paymentCustomer: { pr: "دریافات از/پرداخت به مشتری", en: "Recieve From/Pay To Customer", fr: "paiement" },
    paymentHistory: { pr: "سابقه حساب", en: "Payment History", fr: "antécédents de paiement" },
    paymentPassword: { pr: "رمز عبور  پرداخت آنلاین", en: "Online Payment Password" },
    paymentRbtn: { pr: "پرداخت", en: "Payment", fr: "paiement" },
    payments: { pr: "پرداختها", en: "Payments", fr: "paiements" },
    paymentSupplier: { pr: "دریافات از/پرداخت به تامین کننده", en: "Recieve From/Pay To Supplier", fr: "paiement" },
    paymentType: { pr: "روش پرداخت", en: "Payment Type" },
    paymentUserName: { pr: "نام کاربری پرداخت آنلاین", en: "Online Payment Username" },
    payType: { pr: "نوع پرداخت", en: "Type Of Payment", fr: "Type de payer" },
    periodicPrice: { pr: "قیمت دوره ای", en: "Periodic Price", fr: "périodiques des prix" },
    phone: { pr: "تلفن", en: "Phone", fr: "téléphone" },
    phoneExample: { pr: "مثال تلفن", en: "Phone Example", fr: "" },
    pleaseEnterAValidAge: { pr: "سـن معتبر وارد کنید.", en: "Please Enter A Valid Age", fr: "" },
    pleaseEnterAValidBarcode: { pr: "بارکد معتبر وارد کنید.", en: "Please Enter A Valid Barcode.", fr: "" },
    pleaseEnterAValidBranchCode: { pr: "کد شعبه معتبر وارد کنید", en: "Please Enter A Valid Branch Code.", fr: "" },
    pleaseEnterAValidCode: { pr: "کد معتبر وارد کنید", en: "Please Enter A Valid Code", fr: "" },
    pleaseEnterAValidEmail: { pr: "ایمیل معتبر وارد کنید", en: "Please Enter A Valid Email", fr: "" },
    pleaseEnterAValidFamilyName: { pr: "نام خانوادگی معتبر وارد کنید.", en: "Please Enter A Valid Familyname", fr: "" },
    pleaseEnterAValidFax: { pr: "شماره فاکس معتبروارد کنید", en: "Please Enter A valid Fax.", fr: "" },
    pleaseEnterAValidIntroducerCode: { pr: "کد معرف معتبر وارد کنید", en: "Please Enter A Valid Introducer Code.", fr: "" },
    pleaseEnterAValidItemCode: { pr: "کد کالا معتبر واردکنید", en: "Please Enter A Valid Item Code.", fr: "" },
    pleaseEnterAValidItemName: { pr: "نام کالا معتبر وارد کنید", en: "Please Enter A Valid Item Name.", fr: "" },
    pleaseEnterAValidItemUnit: { pr: "واحد کالا را انتخاب کنید", en: "Please Enter A Valid Item Name.", fr: "" },
    pleaseEnterAValidItemWeight: { pr: "وزن کالا معتبر وارد کنید.", en: "Please Enter A Valid Item Weight.", fr: "" },
    pleaseEnterAvalidMobile: { pr: "شماره موبایل معتبر وارد کنید", en: "Plese Enter A Valid Mobile.", fr: "" },
    pleaseEnterAValidName: { pr: "نام معتبر وارد کنید", en: "Please Enter A Valid Name", fr: "" },
    pleaseEnterAValidPhone: { pr: "شماره تلفن معتبر وارد کنید", en: "Please Enter A Valid Phone.", fr: "" },
    pleaseEnterAValidPhoneNumber: { pr: "لطفا شماره تماس معتبر وارد کنید", en: "Please Enter A Valid Phone Number.", fr: "" },
    pleaseEnterAValidPrice: { pr: "قیمت عمده وارد کنید", en: "Please Enter A Valid Price.", fr: "" },
    pleaseEnterAValidQuantity: { pr: "تعداد معتبر وارد کنید", en: "Please Enter A Valid Quantity.", fr: "" },
    pleaseSelectMainBranch: { pr: "شعبه اصلی را انتخاب کنید", en: "Select Main Branch.", fr: "" },
    pleaseSelectTheTypeNumber: { pr: "نوع شماره را انتخاب کنید", en: "Please Select The Number Type", fr: "" },
    port: { pr: "پورت ایمیل", en: "Email Port" },
    postalCode: { pr: "کد پستی", en: "Postal Code" },
    preOrder: { pr: "پیش فاکتور", en: "Proforma Invoice", fr: "Facture pré" },
    previous: { pr: "<<-قبلی", en: "<<-Previous" },
    price: { pr: "قیمت", en: "Price", fr: "prix" },
    priceInCurrency: { pr: "قیمت (تومان)", en: "Price(USD)", fr: "" },
    pricePerSms: { pr: "قیمت هر پیامک", en: "Price Per Sms", fr: "Prix par SMS" },
    primaryCategory: { pr: "دسته بندی اولیه", en: "Primary Category", fr: "" },
    print: { pr: "چاپ", en: "Print", fr: "imprimer" },
    printBarcode: { pr: "چاپ بارکد", en: "Print Barcodes" },
    profit: { pr: "سود", en: "Profit", fr: "" },
    profitCalculatingAllsaleAllpurchaseAndAverageOfPurchaseAndSellAreIntermsofBaseCurrency: { pr: "محاسبات سود، خرید کل، فروش کل و میانگین قیمت خرید و فروش بر حسب نرخ ارز مبنا می باشد", en: "Profit Calculating ,All sale,All purchase And Average Of Purchase/Sell Are In terms of Base Currency", fr: "" },
    profitPercent: { pr: "درصد سود", en: "Profit Percent", fr: "" },
    profitReport: { pr: "گزارش سود", en: "Profit Report", fr: "" },
    profitSum: { pr: "جمع سود", en: "Total Profit", fr: "" },
    programName: { pr: "نام برنامه", en: "Program Name", fr: "nom du programme" },
    property: { pr: "ویژگی", en: "Property", fr: "propriété" },
    purchaseQuantity: { pr: "تعداد خرید", en: "Purchased Quantity", fr: "" },
    purchaser: { pr: "خریدار", en: "Purchaser" },
    pureProfit: { pr: "سود خالص", en: "Net Profit", fr: "" },
    pureRecieved: { pr: "واریزی خالص", en: "Net Deposite", fr: "" },
    priceDifference: { pr: "اختلاف قیمت", en: "Price Difference" },
    quantityKey: { pr: "تعداد", en: "Quantity" },
    recieve: { pr: "دریافت", en: "Recieve", fr: "obtient" },
    recieverCustomer: { pr: "مشتری دریافت کننده", en: "Reciever Customer", fr: "" },
    recieverName: { pr: "نام گیرنده", en: "Reciever Name", fr: "" },
    refresh: { pr: "به روز", en: "Refresh", fr: "rafraîchir" },
    registerDate: { pr: "تاریخ ثبت", en: "Register Date", fr: "date d'inscrire " },
    registerer: { pr: "ثبت کننده", en: "Registrar", fr: "greffier" },
    registererNamefamily: { pr: "نام و نـام خانوادگی تایید کننده", en: "Registerer Name And Family", fr: "nom et la famille de greffier" },
    registrator: { pr: "ثبت نـام کننده", en: "Registrator", fr: "" },
    remittance: { pr: "حواله", en: "Remittance", fr: "envois de fonds" },
    requiredField: { pr: "این فیلد ضروری است.", en: "This field is required", fr: "ce champ est obligatoire." },
    requiredField: { pr: "این فیلد ضروری است.", en: "This field is required.", fr: "ce champ est obligatoire" },
    requiredFields: { pr: "فیلد های ضروری", en: "Required Fields", fr: "champ obligatoire" },
    requiredFields: { pr: "فیلدهای ضروری", en: "Required Fields", fr: "Les champs obligatoires" },
    resend: { pr: "ارسال مجدد", en: "Resend", fr: "" },
    returned: { pr: "مرجوعی", en: "Returned", fr: "retourneé" },
    returnedCount: { pr: "تعداد مرجوعی", en: "Returned Count", fr: "nombre retourné" },
    returnedSum: { pr: "جمع مرجوعی", en: "Total Returned", fr: "" },
    returnFromBuy: { pr: "مرجوعی از خرید", en: "Return From Buy", fr: "Explique l'achat" },
    returnFromSell: { pr: "مرجوعی", en: "Return From Sell", fr: "Explique Vente" },
    returnPayment: { pr: "برگشت پول", en: "Return Payment" },
    roles: { pr: "نقش ها", en: "Roles", fr: "rôle" },
    row: { pr: "ردیف", en: "Row Number", fr: "numéro de la ligne" },
    salary: { pr: "حقوق و دستمزد ", en: "Salary", fr: "salaire" },
    saleQuantity: { pr: "تعداد فروش", en: "Sales Quantity", fr: "" },
    sameCounter: { pr: "صندوق مبدأ و مقصد نباید یکسان باشد.", en: "Origin counter and destination can't be the same!", fr: "Source de fonds et de destination doivent être les mêmes" },
    sameShop: { pr: "شعبه مبدأ و مقصد نباید یکسان باشد.", en: "Origin branch and destination can't be the same!", fr: "La source de la direction générale et de destination doivent être les mêmes" },
    save: { pr: "ثبت", en: "Save", fr: "enregistrer" },
    saveChanges: { pr: "ثبت تغییرات", en: "Save Changes", fr: "enregistrer les modifications" },
    saveReturned: { pr: "ثبت مرجوعی", en: "Save Returned", fr: "enregistrer retourné" },
    search: { pr: "جستجو", en: "Search", fr: "recherche" },
    searchBY: { pr: "جسـتجـو بر اساس", en: "Search By", fr: "" },
    searchBy: { pr: "فیلتر بر اساس", en: "Search By", fr: "recherche par" },
    searchph: { pr: "جستجو...", en: "Search...", fr: "recherche ..." },
    seasonal: { pr: "فصلی", en: "Seasonal", fr: "" },
    securityAmountFrom: { pr: "مبلغ بیمه از", en: "Socialsecurity Amount From", fr: "" },
    select: { pr: "انتخاب", en: "Select", fr: "" },
    selectColor: { pr: "انتخاب رنگ", en: "Select Color", fr: "" },
    selectCustomers: { pr: "مشتری ها را انتخاب کنید.", en: "Select Customers" },
    selectGender: { pr: "انتخاب جنسیت", en: "Select Gender", fr: "" },
    selectPeriod: { pr: "انتخاب دوره", en: "Select Period", fr: "" },
    selectSize: { pr: "انتخاب جزئیات", en: "Select Details", fr: "" },
    selectStockStatus: { pr: "وضعیت موجودی را انتخاب کنید.", en: "Please Enter A Valid Avalibility Status.", fr: "" },
    sell: { pr: "فروش", en: "Sell", fr: "vendre" },
    sellChart: { pr: "نمودار فروش", en: "Sell Chart", fr: "tableau de vente" },
    seller: { pr: "فروشنده", en: "Seller", fr: "" },
    sellPrice: { pr: "قیمت فروش", en: "Sell Price", fr: "" },
    sellPriceFrom: { pr: "قیمت فروش از", en: "Sale Price From", fr: "" },
    sellRecord: { pr: "سابقه فروش", en: "Sale's Record ", fr: "" },
    sellReturn: { pr: "فروش/مرجوع", en: "Sell/Return", fr: "" },
    sellSum: { pr: "جمع فروش", en: "Total Sale ", fr: "" },
    sellVoucher: { pr: "فروش کارت هدیه", en: "Sell Voucher", fr: "vendre bon" },
    sendDate: { pr: "تاریخ ارسال", en: "Send Date" },
    sendEmail: { pr: "ارسال ایمیل", en: "Send Email" },
    sender: { pr: "فرستنده", en: "Sender", fr: "" },
    senderName: { pr: "نام فرستنده", en: "Sender Name", fr: "" },
    sendingDateFrom: { pr: " تاریخ ارسال از  ", en: "Sending Date From", fr: "" },
    sendMessages: { pr: "ارسال پیامک", en: "SMS Panel", fr: "envoyer un message" },
    sendTime: { pr: "ساعت ارسال", en: "Send Time" },
    sendToAll: { pr: "ارسال به همه", en: "Send To All", fr: "" },
    sendToSelection: { pr: "ارسال به منتخبین", en: "Send to Sellected", fr: "" },
    sendType: { pr: "روش ارسال", en: " Send Method" },
    SentToComunicationCenter: { pr: "هنوز ارسال نشده است.", en: "Sent To Comunication Center" },
    SentToMobile: { pr: "ارسال شد.", en: "Sms Sent" },
    serial: { pr: "سریال", en: "Serial", fr: "en série" },
    setting: { pr: "تنظیمات پایه", en: "Setting", fr: "paramétre" },
    Shop: { pr: "فروشگاه", en: "Store" },
    shopDiscount: { pr: "تخفیف فروشگاه", en: "Shop Discount", fr: "réduction" },
    shoplimit: { pr: "تعداد شعبه", en: "Shop Limit", fr: "nombres des boutiques" },
    show: { pr: "نمایش", en: "Show" },
    side: { pr: "سمت راست صفحه", en: "Side" },
    sign: { pr: "نشان", en: "Symbol", fr: "" },
    sirMadam: { pr: "جناب/سرکار", en: "Sir/Madam", fr: "" },
    size: { pr: "جزئیات", en: "Size", fr: "le taille" },
    size: { pr: "سایز", en: "size", fr: "" },
    sizeCategory: { pr: " گروه جزئیات", en: "Details Group", fr: "" },
    sizeIsEmpty: { pr: "جزئیات را انتخاب کنید.", en: "Select Details", fr: "Sélectionnez Détails" },
    sizeUnit: { pr: "واحد جزئیات", en: "Details Unit", fr: "" },
    Sms: { pr: "پیامک", en: "Sms" },
    smsCredit: { pr: "اعتبار پیامک", en: "SMS Credit", fr: "crédit SMS" },
    smslimit: { pr: "اعتبار پیامک", en: "Sms Limit", fr: "validité de massage" },
    smsNumber: { pr: "شماره پیامک", en: "Sms Number", fr: "numéro du message" },
    smsPass: { pr: "رمز عبور پنل پیامک", en: "SMS Password" },
    smsUser: { pr: "نام کاربری پنل پیامک", en: "SMS Username" },
    social: { pr: "بیمه", en: "Social", fr: "l'assurance" },
    socialAmount: { pr: "مبلغ بیمه", en: "Social Amount", fr: "montant d'assurance" },
    socialSecurity: { pr: "بیمه ", en: "Socialsecurity", fr: "l'assurance" },
    sort: { pr: "مرتب سازی", en: "Sort", fr: "" },
    spenderCustomer: { pr: "مشتری خرج کننده", en: "Spender Customer", fr: "" },
    spendingDate: { pr: "تاریخ خرج", en: "Spend Date", fr: "" },
    spendingDateOf: { pr: "تاریخ خرج از", en: "Spend Date From", fr: "" },
    spoiledQuantity: { pr: "تعداد خراب", en: "Brokened Quantity", fr: "" },
    spoiledSafe: { pr: "سالم/خراب", en: "Fine/Broken", fr: "" },
    startingDate: { pr: "تاریخ شروع", en: "Starting Date" },
    statistic: { pr: "آمار بازدید", en: "Statistic" },
    status: { pr: "وضعیت", en: "Status", fr: "etat" },
    stockInCurrency: { pr: "موجودی به تومان", en: "stok in USD", fr: "stock in euro" },
    stockStatus: { pr: "وضعیت موجودی", en: "Avalibility Status", fr: "" },
    store: { pr: "فروشگاه", en: "Store", fr: "Boutique" },
    storeSetting: { pr: "تنظیمات فروشگاه ", en: "Setup", fr: "paramétre de boutique" },
    subCategory: { pr: "زیرگروه", en: "Sub Category", fr: "sous-groupe" },
    subject: { pr: " موضوع", en: "Subject", fr: "" },
    subscriptionFee: { pr: "مبلغ  اشتراک", en: " Subscription Amount", fr: "commission de souscription" },
    suggestionQuantity: { pr: " تعداد کالای پیشنهادی", en: "Suggested Item Quantity", fr: "" },
    sum: { pr: "کل", en: "Total", fr: "le somme" },
    sumAllPayments: { pr: "جمع کل برداشتها", en: "Total All Payments", fr: "somme des paiements" },
    sumCashPayments: { pr: "جمع برداشتهای نقدی", en: "Total Cash Payments", fr: "Somme des paiements en espèces" },
    sumCashPayTo: { pr: "جمع برداشت های نقدی به", en: "Total Cash Withdrawal To", fr: "" },
    sumCashReceiveOf: { pr: "جمع واریز های نقدی از", en: "Total Cash Deposite Of", fr: "" },
    sumChequePayments: { pr: "جمع چک های برداشتی", en: "Total Cheque Payments", fr: "chèque percevoir le paiement" },
    sumCommission: { pr: "جمع پورسانت", en: "Total Commission", fr: "total des commissions" },
    sumPayChequeTo: { pr: "جمع چک های برداشتی به", en: "Total Withdrawaled Cheque To", fr: "" },
    sumRecieved: { pr: "جمع واریزی", en: "Total Deposite", fr: "total reçus" },
    sumRecievedChequeOf: { pr: "جمع چک های واریزی از", en: "Total Deposited Cheque Of", fr: "" },
    sumRecievedOf: { pr: "جمع واریزی از", en: "Total deposite Of", fr: "" },
    sumVoucherPAyments: { pr: "جمع کارت های هدیه", en: "Total Voucher Payments", fr: "somme de coupon" },
    sumWithdrawalTo: { pr: "جمع برداشتی به", en: "Total withdrawal Of", fr: "" },
    supplier: { pr: "تامین کننده ", en: "Supplier", fr: "fournisseur" },
    suppliers: { pr: "تامین کننده ها", en: "Suppliers", fr: "fournisseur" },
    telefax: { pr: "شماره تلفکس", en: "Telefax Number", fr: "" },
    terminalId: { pr: "شماره ترمینال  پرداخت آنلاین", en: "Online Payment Terminal ID" },
    text: { pr: "متن", en: "Text", fr: "" },
    title: { pr: "عنوان", en: "title", fr: "" },
    to: { pr: "تا", en: "To", fr: "jusqu'à" },
    toBranch: { pr: "شعبه مقصد", en: "Destination Branch", fr: "" },
    toCounter: { pr: "صندوق مقصد", en: "Destination Counter", fr: "caisse de destination" },
    toDate: { pr: "تا تاریخ", en: "To Date", fr: "jusqu'à(la date)" },
    totalAmount: { pr: "قیمت کل", en: "Total Amount", fr: "le coût total" },
    totalAmount: { pr: "مبلغ کل", en: "Total Amount", fr: "montant total" },
    totalBuy: { pr: "کل خرید", en: "Total Purchase", fr: "" },
    totalCash: { pr: "کل برداشتی", en: "Total Withdrawal", fr: "" },
    totalExpenses: { pr: "هزینه های کل", en: "Total Expenses", fr: "" },
    totalOtherExpenses: { pr: "کل هزینه های متفرقه :", en: "Total Miscellaneous Expenses", fr: "" },
    totalPrice: { pr: "ارزش کل", en: "Total Value" },
    totalQuantity: { pr: "تعداد کل", en: "Total Quantity" },
    totalRecieved: { pr: "کل واریزی", en: "Total Deposite", fr: "" },
    totalSalaryExpenses: { pr: "کل هزینه های حقوق:", en: "Total Salary Expenses", fr: "" },
    totalSell: { pr: "کل فروش", en: "Total Sale", fr: "" },
    totalSocialSecurityExpenses: { pr: "کل هزینه های بیمه:", en: "Total Socialsecurity Expenses", fr: "" },
    totalSum: { pr: "جمع کل", en: "Total", fr: "" },
    transfer: { pr: "انتقال", en: "Transfer", fr: "" },
    transferFrom: { pr: "انتقال از", en: "Transfer From", fr: "Transfert de" },
    transferQuantity: { pr: "انتقال از شعبه", en: "Transfer Quantity" },
    transfers: { pr: "انتقالی", en: "Transer", fr: "transferts" },
    transferTo: { pr: "انتقال به ", en: "Transfer To", fr: "Transfert à l'" },
    translate: { pr: "ترجمه", en: "Translate", fr: "" },
    type: { pr: "نوع", en: "Type", fr: "" },
    typeNumber: { pr: "نوع شماره", en: "Number Type", fr: "" },
    undefined: { pr: "تعریف نشده", en: "Undefined", fr: "indéfini" },
    unitKey: { pr: "واحد", en: "Unit", fr: "unité" },
    unitDiscount: { pr: "تخفیف واحد", en: "Unit Discount", fr: "" },
    unknown: { pr: "نا معلوم", en: "UNKNOWN!" },
    update: { pr: "بروزرسانی", en: "Update" },
    upDown: { pr: "بالا به پایین", en: "Up-down", fr: "" },
    username: { pr: "کاربر", en: "username", fr: "" },
    userName: { pr: "نام کاربری", en: "Username", fr: "nom d'utilisateur" },
    usernameCode: { pr: "کد کاربری", en: "Username Code", fr: "" },
    usernameExist: { pr: "این نام کاربری قبلاً ثبت شده، نام کاربری را تغییر دهید.", en: "The username is already in use,try another!", fr: "Le nom d'utilisateur est déjà utilisé." },
    valid: { pr: "معتبر", en: "Valid", fr: "" },
    value: { pr: "مقدار", en: "Value", fr: "valeur" },
    viewStatus: { pr: "مشاهده وضعیت", en: "View Status", fr: "" },
    voucher: { pr: "کارت هدیه", en: "Voucher", fr: "coupon" },
    voucherCost: { pr: "ارزش کارت", en: "Voucher Cost", fr: "coût de coupon" },
    voucherEmpty: { pr: "شماره کارتی با این مشخصات وجود ندارد.", en: "Gift card with this number does not exist.", fr: "Carte-cadeau avec ce numéro n'existe pas" },
    voucherFee: { pr: "مبلغ کارت هدیه", en: "Voucher Amount", fr: "" },
    voucherList: { pr: "کارت هدیه", en: "Voucher List", fr: "liste coupon" },
    voucherNo: { pr: "شماره کارت هدیه", en: "Voucher Number", fr: "numéro du coupon" },
    voucherOwner: { pr: "صاحب کارت", en: "Voucher Owner", fr: "propriétaire de coupon" },
    voucherReceive: { pr: "دریافت کارت هدیه", en: "Voucher Receive", fr: "obtenir des coupons" },
    voucherSell: { pr: "فروش کارت هدیه", en: "Voucher Sell", fr: "coupon vendre" },
    weeK: { pr: "1هفته", en: "1Week", fr: "" },
    weekly: { pr: "هفتگی", en: "Weekly", fr: "" },
    wholesaleBuyer: { pr: "خریدار عمده", en: "wholesale Buyer" },
    wholesaleOrder: { pr: "ثبت فاکتور عمده", en: "Wholesale Order", fr: "facture de gros" },
    wholesalePrice: { pr: "قیمت عمده", en: "Wholesale Price", fr: "" },
    withdrawalDateOf: { pr: " تاریخ برداشت از", en: "Withdrawal Date Of", fr: "" },
    withoutColorSize: { pr: " بدون رنگ و جزئیات", en: "Without Color And Details", fr: "" },
    wrongPassword: { pr: "رمز عبور اشتباه است!.", en: "Password is invalid!", fr: "Mot de passe est incorrect" },
    WrongUserOrPass: { pr: "نام کاربری یا رمز عبور اشتباه است.", en: "Username or password is incorrect!", fr: "Nom d'utilisateur ou mot de passe est incorrect" },
    year: { pr: "1سال", en: "1Year", fr: "" },
    yes: { pr: "بلی", en: "Yes" },
    priceType: { pr: "نوع قیمت", en: "Price Type" },
    setPayment: { pr: "پرداخت شود", en: "Set Payment" },
    noPayment: { pr: "بدون پرداخت", en: "Without Payment" },
    quantityCorrection: { pr: "اصلاح تعداد", en: "Quantity Correction" },
    forQuantityCorrection: { pr: " بابت اصلاح تعداد", en: "For Quantity Correction" },
    supInvoice: { pr: "(فاکتور تأمین کننده)", en: "(Supplier Invoice)" },
    netBalance: { pr: "باقیمانده خالص", en: "Net Balance" },
    cusInvoice: { pr: "(فاکتور مشتری)", en: "(Customer Invoice)" },
    orderType: { pr: "نوع سند", en: "Order Type" },
    totalValue: { pr: "ارزش کل", en: "Total Value" }
};