//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18408.
// 
#pragma warning disable 1591

namespace MapiOnline.ir.afe.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BoxServiceSoap", Namespace="http://www.afe.ir/")]
    public partial class BoxService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendMessageOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendMessagePeerToPeerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessageStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetMessagesStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRemainingCreditOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BoxService() {
            this.Url = global::MapiOnline.Properties.Settings.Default.MapiOnline_ir_afe_www_BoxService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendMessageCompletedEventHandler SendMessageCompleted;
        
        /// <remarks/>
        public event SendMessagePeerToPeerCompletedEventHandler SendMessagePeerToPeerCompleted;
        
        /// <remarks/>
        public event GetMessageIDCompletedEventHandler GetMessageIDCompleted;
        
        /// <remarks/>
        public event GetMessageStatusCompletedEventHandler GetMessageStatusCompleted;
        
        /// <remarks/>
        public event GetMessagesStatusCompletedEventHandler GetMessagesStatusCompleted;
        
        /// <remarks/>
        public event GetRemainingCreditCompletedEventHandler GetRemainingCreditCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afe.ir/SendMessage", RequestNamespace="http://www.afe.ir/", ResponseNamespace="http://www.afe.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SendMessage(string Username, string Password, string Number, string[] Mobile, string Message, string Type, [System.Xml.Serialization.XmlArrayItemAttribute()] System.Nullable<long>[] CheckingMessageID) {
            object[] results = this.Invoke("SendMessage", new object[] {
                        Username,
                        Password,
                        Number,
                        Mobile,
                        Message,
                        Type,
                        CheckingMessageID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SendMessageAsync(string Username, string Password, string Number, string[] Mobile, string Message, string Type, System.Nullable<long>[] CheckingMessageID) {
            this.SendMessageAsync(Username, Password, Number, Mobile, Message, Type, CheckingMessageID, null);
        }
        
        /// <remarks/>
        public void SendMessageAsync(string Username, string Password, string Number, string[] Mobile, string Message, string Type, System.Nullable<long>[] CheckingMessageID, object userState) {
            if ((this.SendMessageOperationCompleted == null)) {
                this.SendMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessageOperationCompleted);
            }
            this.InvokeAsync("SendMessage", new object[] {
                        Username,
                        Password,
                        Number,
                        Mobile,
                        Message,
                        Type,
                        CheckingMessageID}, this.SendMessageOperationCompleted, userState);
        }
        
        private void OnSendMessageOperationCompleted(object arg) {
            if ((this.SendMessageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessageCompleted(this, new SendMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afe.ir/SendMessagePeerToPeer", RequestNamespace="http://www.afe.ir/", ResponseNamespace="http://www.afe.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SendMessagePeerToPeer(string Username, string Password, string[] Number, string[] Mobile, string[] Message, string[] Type, [System.Xml.Serialization.XmlArrayItemAttribute()] System.Nullable<long>[] CheckingMessageID) {
            object[] results = this.Invoke("SendMessagePeerToPeer", new object[] {
                        Username,
                        Password,
                        Number,
                        Mobile,
                        Message,
                        Type,
                        CheckingMessageID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SendMessagePeerToPeerAsync(string Username, string Password, string[] Number, string[] Mobile, string[] Message, string[] Type, System.Nullable<long>[] CheckingMessageID) {
            this.SendMessagePeerToPeerAsync(Username, Password, Number, Mobile, Message, Type, CheckingMessageID, null);
        }
        
        /// <remarks/>
        public void SendMessagePeerToPeerAsync(string Username, string Password, string[] Number, string[] Mobile, string[] Message, string[] Type, System.Nullable<long>[] CheckingMessageID, object userState) {
            if ((this.SendMessagePeerToPeerOperationCompleted == null)) {
                this.SendMessagePeerToPeerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendMessagePeerToPeerOperationCompleted);
            }
            this.InvokeAsync("SendMessagePeerToPeer", new object[] {
                        Username,
                        Password,
                        Number,
                        Mobile,
                        Message,
                        Type,
                        CheckingMessageID}, this.SendMessagePeerToPeerOperationCompleted, userState);
        }
        
        private void OnSendMessagePeerToPeerOperationCompleted(object arg) {
            if ((this.SendMessagePeerToPeerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendMessagePeerToPeerCompleted(this, new SendMessagePeerToPeerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afe.ir/GetMessageID", RequestNamespace="http://www.afe.ir/", ResponseNamespace="http://www.afe.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessageID(string Username, string Password, long CheckingMessageSentID) {
            object[] results = this.Invoke("GetMessageID", new object[] {
                        Username,
                        Password,
                        CheckingMessageSentID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageIDAsync(string Username, string Password, long CheckingMessageSentID) {
            this.GetMessageIDAsync(Username, Password, CheckingMessageSentID, null);
        }
        
        /// <remarks/>
        public void GetMessageIDAsync(string Username, string Password, long CheckingMessageSentID, object userState) {
            if ((this.GetMessageIDOperationCompleted == null)) {
                this.GetMessageIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageIDOperationCompleted);
            }
            this.InvokeAsync("GetMessageID", new object[] {
                        Username,
                        Password,
                        CheckingMessageSentID}, this.GetMessageIDOperationCompleted, userState);
        }
        
        private void OnGetMessageIDOperationCompleted(object arg) {
            if ((this.GetMessageIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageIDCompleted(this, new GetMessageIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afe.ir/GetMessageStatus", RequestNamespace="http://www.afe.ir/", ResponseNamespace="http://www.afe.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetMessageStatus(string Username, string Password, string SmsID) {
            object[] results = this.Invoke("GetMessageStatus", new object[] {
                        Username,
                        Password,
                        SmsID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetMessageStatusAsync(string Username, string Password, string SmsID) {
            this.GetMessageStatusAsync(Username, Password, SmsID, null);
        }
        
        /// <remarks/>
        public void GetMessageStatusAsync(string Username, string Password, string SmsID, object userState) {
            if ((this.GetMessageStatusOperationCompleted == null)) {
                this.GetMessageStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessageStatusOperationCompleted);
            }
            this.InvokeAsync("GetMessageStatus", new object[] {
                        Username,
                        Password,
                        SmsID}, this.GetMessageStatusOperationCompleted, userState);
        }
        
        private void OnGetMessageStatusOperationCompleted(object arg) {
            if ((this.GetMessageStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessageStatusCompleted(this, new GetMessageStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afe.ir/GetMessagesStatus", RequestNamespace="http://www.afe.ir/", ResponseNamespace="http://www.afe.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetMessagesStatus(string Username, string Password, string[] SmsID) {
            object[] results = this.Invoke("GetMessagesStatus", new object[] {
                        Username,
                        Password,
                        SmsID});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetMessagesStatusAsync(string Username, string Password, string[] SmsID) {
            this.GetMessagesStatusAsync(Username, Password, SmsID, null);
        }
        
        /// <remarks/>
        public void GetMessagesStatusAsync(string Username, string Password, string[] SmsID, object userState) {
            if ((this.GetMessagesStatusOperationCompleted == null)) {
                this.GetMessagesStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetMessagesStatusOperationCompleted);
            }
            this.InvokeAsync("GetMessagesStatus", new object[] {
                        Username,
                        Password,
                        SmsID}, this.GetMessagesStatusOperationCompleted, userState);
        }
        
        private void OnGetMessagesStatusOperationCompleted(object arg) {
            if ((this.GetMessagesStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetMessagesStatusCompleted(this, new GetMessagesStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.afe.ir/GetRemainingCredit", RequestNamespace="http://www.afe.ir/", ResponseNamespace="http://www.afe.ir/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetRemainingCredit(string Username, string Password) {
            object[] results = this.Invoke("GetRemainingCredit", new object[] {
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRemainingCreditAsync(string Username, string Password) {
            this.GetRemainingCreditAsync(Username, Password, null);
        }
        
        /// <remarks/>
        public void GetRemainingCreditAsync(string Username, string Password, object userState) {
            if ((this.GetRemainingCreditOperationCompleted == null)) {
                this.GetRemainingCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRemainingCreditOperationCompleted);
            }
            this.InvokeAsync("GetRemainingCredit", new object[] {
                        Username,
                        Password}, this.GetRemainingCreditOperationCompleted, userState);
        }
        
        private void OnGetRemainingCreditOperationCompleted(object arg) {
            if ((this.GetRemainingCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRemainingCreditCompleted(this, new GetRemainingCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendMessageCompletedEventHandler(object sender, SendMessageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SendMessagePeerToPeerCompletedEventHandler(object sender, SendMessagePeerToPeerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendMessagePeerToPeerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendMessagePeerToPeerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMessageIDCompletedEventHandler(object sender, GetMessageIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMessageStatusCompletedEventHandler(object sender, GetMessageStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessageStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessageStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetMessagesStatusCompletedEventHandler(object sender, GetMessagesStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetMessagesStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetMessagesStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetRemainingCreditCompletedEventHandler(object sender, GetRemainingCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRemainingCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRemainingCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591